version: "3.9"

services:
  mongodb:
    container_name: mongodb_service
    image: "mongo:latest"

  redis:
    container_name: redis_service
    image: "redis:latest"

  app:
    container_name: hello-wops
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - redis
      - mongodb
    environment:
      - MONGO_HOST=mongodb_service
      - MONGO_PORT=27017
      - REDIS_HOST=redis_service
      - REDIS_PORT=6379
      - PORT=3000
    ports:
      - 3000:3000
    build:
      context: .
